name: Klokan Technologies
favicon: null
layout_spectrum: 0.6642971246037632
typography_spectrum: 0.7708376632072031
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5297795466613024
  lightness: 0.7002629768103361
  saturation: 0.9319530301727355
  rhythmicContrast: 0.6408633047249168
purpose: []
