name: Klokan Technologies
favicon: null
layout_spectrum: 0
typography_spectrum: 0.71742
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.9319530301727355
  rhythmicContrast: 0.75
purpose: []
